### ISSUE TITLE
Use silhouette as token [FEATURE]

### ISSUE THREAD

**Issue by Acknar** [prolice/starwars-silhouette#1]
Would it be possible to add an option to use the top view silhouette as the token by default rather than the image?

**Comment by prolice** [comment]
v1.0.0 ;-)

**Comment by prolice** [comment]
released

**Comment by Acknar** [comment]
I just checked out the update (congrats on the 1.0 release by the way ;) ). The silhouettes now work as tokens but I imagined the token being changed independently of the profile image and thumbnail to keep them as the images. Can this be achieved with your module as I have had trouble trying to change the silhouettes manually with this mod enabled (it seems to automatically overwrite the token selection with it's own)
